#!/usr/bin/env node
// Copies the SDK-free slices of the shared submodule (../src/common/src/shared)
// into functions/src/shared so the Cloud Functions compile against the same
// contract/config/enums the three client apps use. Runs automatically as
// the `prebuild` npm script (so `npm run build`, `npm test`, `npm run serve`
// and the firebase predeploy all get a fresh copy); functions/src/shared is
// gitignored - never edit it by hand, edit the submodule and re-run.
//
// Why a copy and not an import/symlink: `firebase deploy` uploads only the
// functions/ directory, so nothing outside it can be referenced at runtime,
// and npm `file:` deps/symlinks have a history of packaging trouble with the
// Firebase CLI. Only slices with NO client-SDK imports are copied (the
// shared models import firebase/firestore's Timestamp type, which functions
// - on firebase-admin - can't resolve).
const fs = require("fs");
const path = require("path");

const SLICES = ["config", "contract", "lists"];
const from = path.resolve(__dirname, "..", "..", "src", "common", "src", "shared");
const to = path.resolve(__dirname, "..", "src", "shared");

if (!fs.existsSync(from)) {
  console.error(`[sync-shared] shared submodule not found at ${from} - run \`git submodule update --init\` in the repo root.`);
  process.exit(1);
}

fs.rmSync(to, {recursive: true, force: true});
let copied = 0;
for (const slice of SLICES) {
  const src = path.join(from, slice);
  if (!fs.existsSync(src)) continue;
  fs.cpSync(src, path.join(to, slice), {
    recursive: true,
    filter: (p) => fs.statSync(p).isDirectory() || (p.endsWith(".ts") && !p.endsWith(".spec.ts")),
  });
  copied += 1;
}
fs.writeFileSync(
  path.join(to, "README.md"),
  "GENERATED by functions/scripts/sync-shared.js from ../../src/common/src/shared - do not edit here; edit the shared submodule.\n"
);
console.log(`[sync-shared] copied ${copied} slice(s) into ${path.relative(process.cwd(), to)}`);
